config_default_image:
  type: mapping
  mapping:
    uri:
      type: string
      label: 'Image URI'
    alt:
      type: label
      label: 'Alternative text'
    title:
      type: label
      label: 'Title'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
