field.formatter.settings.config_default_image:
  type: mapping
  label: 'Image field display format settings'
  field_default_image:
    type: mapping
    mapping:
      image_link:
        type: string
        label: 'Link image to'
      image_style:
        type: string
        label: 'Image style'
      default_image:
        type: field_default_image
        label: 'Default image'
