<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_preprocess_HOOK()
 *
 * @param $variables
 */
function hsk_images_preprocess_node(&$variables) {
  if(!empty($variables['node']->field_main_image_teaser_only->value)) {
    if($variables['node']->field_main_image_teaser_only->value = 1) {
      $variables['attributes']['class'][] = 'main-image-teaser-only';
    }
  }
}
