name: Config Default SVG Image
type: module
description: 'SVG-compatible image field formatter allowing to set a default image deployable through config management'
package: Media
core: 8.x
core_version_requirement: ^8 || ^9 || ^10
dependencies:
  - config_default_image:config_default_image
  - svg_image:svg_image

# Information added by Drupal.org packaging script on 2023-01-09
version: '8.x-2.0-beta2'
project: 'config_default_image'
datestamp: 1673275248
