responsive_tables_filter.settings:
  type: config_object
  mapping:
    views_enabled:
      type: string
      label: "Views enabled"
    views_tablesaw_mode:
      type: string
      label: "Views tablesaw mode"
