name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
# version: VERSION
# core: 8.x
hidden: true
dependencies:
  - action
  - language
  - tour

# Information added by Drupal.org packaging script on 2015-05-27
version: '8.0.0-beta11'
core: '8.x'
project: 'drupal'
datestamp: 1432759049
