<?php

use Drupal\Core\Url;
use Laminas\Diactoros\Uri;

function hsk_block_theme() {
  return [
    'header_slideshow_block' => [
      'variables' => [
        'slides' =>[],
      ],
    ],
    'page_paragraph_top_block' => [
      'variables' => [
        'paragraphs' =>[],
      ],
    ],
  ];
}


function hsk_block_preprocess_paragraph__slideshow_image__slideshow(&$variables) {
  $paragraph = $variables['paragraph'];
  if(!empty($paragraph->field_sli_link_heading->uri)) {
    $uri = $paragraph->field_sli_link_heading->uri;
    $url = Url::fromUri($uri)->toString();
    $variables['slide_link'] = $url;
    $peter = 7;
  }
}
