<?php

namespace Drupal\hsk_views\Plugin\views\sort;

use Drupal\Core\Cache\CacheableDependencyInterface;
use Drupal\Core\Cache\UncacheableDependencyTrait;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Plugin\views\sort\SortPluginBase;

/**
 * Handle a random sort.
 *
 * @ViewsSort("header_sl_sort")
 */
class HeaderSliDeltaSort extends SortPluginBase implements CacheableDependencyInterface {

//  use UncacheableDependencyTrait;
//
//  /**
//   * {@inheritdoc}
//   */
//  public function usesGroupBy() {
//    return FALSE;
//  }
//
//  public function query() {
//    $this->query->addOrderBy('rand');
//  }
//
//  public function buildOptionsForm(&$form, FormStateInterface $form_state) {
//    parent::buildOptionsForm($form, $form_state);
//    $form['order']['#access'] = FALSE;
//  }

public function query()
{
  $this->ensureMyTable();
  $delta = $this->tableAlias . '.' . $this->realField;
//  $this->query()->addOrderBy($delta);
//  ksm($delta);
  $this->query->addOrderBy($delta);
  $peter = 7;
}

public function buildOptionsForm(&$form, FormStateInterface $form_state)
{
  parent::buildOptionsForm($form, $form_state); // TODO: Change the autogenerated stub
  $willi = 3;
}

}
