entityconnect.administration_config:
  type: config_object
  label: 'Entity connect admin settings'
  mapping:
    buttons:
      type: mapping
      label: 'Buttons'
      mapping:
        button_add:
          type: integer
          label: ‘Display add button’
        button_edit:
          type: integer
          label: ‘Display edit button’
    icons:
      type: mapping
      label: 'Icons'
      mapping:
        icon_add:
          type: integer
          label: ‘Icon setting for add button’
        icon_edit:
          type: integer
          label: ‘Icon setting for edit button’

field.field.*.*.*.third_party.entityconnect:
  type: mapping
  label: 'Entity connect field settings'
  mapping:
    buttons:
      type: mapping
      label: 'Buttons'
      mapping:
        button_add:
          type: integer
          label: ‘Display add button’
        button_edit:
          type: integer
          label: ‘Display edit button’
    icons:
      type: mapping
      label: 'Icons'
      mapping:
        icon_add:
          type: integer
          label: ‘Icon setting for add button’
        icon_edit:
          type: integer
          label: ‘Icon setting for edit button’
