field.field_settings.timefield:
  type: mapping
  label: 'Timefield settings'
  mapping:
    totime:
      type: string
      label: 'To Time'
    weekly_summary:
      type: integer
      label: 'Add Weekly Repeat Checkboxes'
    weekly_summary_with_label:
      type: integer
      label: 'Add Weekly Repeat Checkboxes with Label for each Time'
