filename: hsk-db
path: 'private://backup_db'
date: html_date
settings:
  include_tables: null
  exclude_tables: null
  compress: None
  no_data: false
  add_drop_table: true
  single_transaction: true
  lock_tables: true
  add_locks: true
  extended_insert: true
  complete_insert: false
  disable_keys: true
  where: ''
  no_create_info: false
  skip_triggers: false
  add_drop_trigger: true
  routines: false
  hex_blob: true
  databases: false
  add_drop_database: true
  skip_tz_utc: false
  no_autocommit: true
  default_character_set: utf8
  skip_comments: false
  skip_dump_date: false
_core:
  default_config_hash: JUaH_O-74oul7rGXkphoJleru7uDEtBknxuRAtwsAdw
langcode: de
