cookie_lifetime: 100
domain: ''
domains_option: 1
domains_list: ''
eu_only: null
eu_only_js: null
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: false
langcode: de
popup_agreed:
  value: '<h2>Vielen Dank für das Akzeptieren der Cookies</h2><p>Sie können diese Meldung jetzt ausblenden oder mehr über Cookies erfahren.</p>'
  format: restricted_html
popup_agree_button_message: 'Ich stimme zu'
popup_agreed_enabled: false
popup_bg_hex: 0779bf
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
popup_delay: 1000
show_disagree_button: false
popup_disagree_button_message: 'Weitere Informationen'
popup_enabled: true
popup_find_more_button_message: 'Weitere Informationen'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Hide
popup_info:
  value: "<p>Wir benutzen Cookies auf dieser Seite, um die Bedienbarkeit für Sie zu verbessern.<br />\r\nWeitere Informationen zu Cookies finden Sie auf unserer <a data-entity-type=\"node\" data-entity-uuid=\"17550b5d-3da7-4a52-96e8-beb8878510cc\" href=\"/node/368\">Datenschutzerklärung</a>.</p>\r\n"
  format: basic_html
popup_info_template: new
mobile_popup_info:
  value: ''
  format: basic_html
mobile_breakpoint: 768
popup_link: /node/359
popup_link_new_window: false
popup_position: true
fixed_top_position: true
popup_text_hex: ffffff
popup_width: 100%
use_bare_css: false
disagree_do_not_show_popup: false
reload_page: false
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: false
use_mobile_message: false
_core:
  default_config_hash: OlBvbDcm2PUT2i28p3oNpuKaUKbbK4qjfrAyYxvd0B8
method: default
disagree_button_label: 'Nein, danke'
disabled_javascripts: ''
whitelisted_cookies: ''
consent_storage_method: do_not_store
withdraw_message:
  value: '<h2>We use cookies on this site to enhance your user experience</h2><p>You have given your consent for us to set cookies.</p>'
  format: basic_html
withdraw_action_button_label: 'Zustimmung zurückziehen'
withdraw_tab_button_label: Datenschutzeinstellungen
withdraw_enabled: false
