<?php
/**
 * @file
 * @see \Drupal\node\Tests\NodeQueryAlterTest
 * @see \Drupal\node\Tests\NodeAccessBaseTableTest
 */

use Drupal\Core\Access\AccessResult;
use Drupal\node\NodeInterface;

/**
 * Implements node_view_permissions_node_access().
 */
function node_view_permissions_node_access(NodeInterface $node, $op, $account) {
  $type = $node->bundle();
  switch ($op) {
    case 'create':
    case 'update':
    case 'delete':
      return AccessResult::neutral();
    default:
      if ($account->hasPermission('view any ' . $type . ' content', $account)) {
        return AccessResult::allowed()->cachePerPermissions();
      } else if (($account->hasPermission('view own ' . $type . ' content', $account)) && ($account->id() == $node->getOwnerId())) {
        return AccessResult::allowed()->cacheUntilEntityChanges($node);
      } else {
	return AccessResult::forbidden();
      }
  }
}
